---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---


```{r setup, include=FALSE}
options(repos = c(CRAN = "https://cloud.r-project.org"))
```

```{r}
#1a Import data from text file
data <- read.delim("C:\\Users\\merve\\OneDrive\\Desktop\\Su_raw_matrix.txt")

#1b
mean(data$Liver_2.CEL) # Calculate the mean of Liver_2.CEL column
sd(data$Liver_2.CEL) # Calculate the standard deviation of Liver_2.CEL column

#1c
colMeans(data)  # Compute the average of each column
colSums(data)   # Compute the total of each column
```

```{r}

#2

set.seed(123) # Set seed for reproducibility

#2a

a <- rnorm(10000, mean=0, sd= 0.2) # Generate 10,000 random numbers from N(0, 0.2)
# Save histogram as PNG
png("histogram_a.png", width=800, height=600)
hist(a, main = "Histogram: mean=0, sd=0.2", xlab = "Values",xlim=c(-5,5) )
dev.off()

#2b

b <- rnorm(10000, mean=0, sd= 0.5) # Generate 10,000 random numbers from N(0, 0.5)
# Save histogram as PNG
png("histogram_b.png", width=800, height=600)
hist(b, main = "Histogram: mean=0, sd=0.5", xlab = "Values", xlim=c(-5,5))
dev.off()

#In both graphs, the mean appears around 0, but in graph (a), the distribution is narrower and more concentrated because the standard deviation is small, whereas in graph (b), it is wider and the values are further from the mean

```


```{r}
#install.packages("ggplot2")

library(ggplot2) # Import ggplot2 package

dat <- data.frame(cond = factor(rep(c("A","B"), each=200)),
rating = c(rnorm(200),rnorm(200, mean=.8)))

#3b Overlaid histograms
ggplot(dat, aes(x=rating, fill=cond)) +
geom_histogram(binwidth=.5, alpha=.5, position="identity")

#3c Interleaved histograms
ggplot(dat, aes(x=rating, fill=cond)) + geom_histogram(binwidth=.5, position="dodge")

#3d Density plots
ggplot(dat, aes(x=rating, colour=cond)) + geom_density()

#3e Density plots with semitransparent fill
ggplot(dat, aes(x=rating, fill=cond)) + geom_density(alpha=.3)

```

```{r}

#3f

diabetes_data <- read.csv("C:\\Users\\merve\\OneDrive\\Desktop\\diabetes_train.csv")

#Overlaid histograms
p1 <- ggplot(diabetes_data, aes(x=mass, fill=class)) +
geom_histogram(binwidth=.5, alpha=.5, position="identity")
ggsave("overlaid_hist.png", plot = p1, width = 8, height = 6)

#Interleaved histograms
p2 <- ggplot(diabetes_data, aes(x=mass, fill=class)) + geom_histogram(binwidth=.5, position="dodge")
ggsave("interleaved_hist.png", plot = p2, width = 8, height = 6)

#Density plots
p3 <- ggplot(diabetes_data, aes(x=mass, colour=class)) + geom_density()
ggsave("density_plots.png", plot = p3, width = 8, height = 6)

#Density plots with semitransparent fill
p4 <- ggplot(diabetes_data, aes(x=mass, fill=class)) + geom_density(alpha=.3)
ggsave("dp_withfill.png", plot = p4, width = 8, height = 6)

```

```{r}

#4

remove.packages("tidyverse")
install.packages("tidyverse")

library(tidyverse)
library(tidyr)

passengers <- read.csv("C:\\Users\\merve\\OneDrive\\Desktop\\titanic.csv")
  
#4a

passengers %>%
  drop_na() %>%  # Remove rows with NA values
  summary()       # Show summary statistics of each column

#4b

passengers %>%
  filter(Sex == "male")  # Keep only male passengers

#4c

passengers %>%
  arrange(desc(Fare))  # Sort by Fare in descending order

#4d

passengers %>%
  mutate(FamSize = Parch + SibSp)  # Create new column 'FamSize' as the sum of 'Parch' and 'SibSp'

#4e

passengers %>%
  group_by(Sex) %>% 
  summarise(
    meanFare = mean(Fare),  # Average Fare per Sex
    numSurv = sum(Survived) # Total number of survivors per Sex
  )
```


```{r}

#5 

quantile(diabetes_data$skin, probs= c(0.1, 0.3, 0.5, 0.6))
```